### ISSUE TITLE
Making this work with cakephp

### ISSUE THREAD

**Issue by gabrielconfused** [jmitchell38488/oauth2-fitbit#5]
Hello,

I just installed this on my cakephp version 2.5.4
I used composer to install this in the vendor folder
I already changed the variables for ClientID ClientSecret etc
also changed the directory for the namespace
but I get this error with the namespace
Error: syntax error, unexpected 'use' (T_USE)  
and this without the namespace
Error: Class 'FitBitAuthorization' not found    

thank you very much

**Comment by jmitchell38488** [comment]
Whats the php error stack say? If paste that I can help you.

**Comment by gabrielconfused** [comment]
Is this it?
This is my error log

2016-09-22 01:22:45 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE) in [D:\xampp\htdocs\isaserver\app\Controller\AppSyncsController.php, line 20]
2016-09-22 01:22:45 Error: [FatalErrorException] syntax error, unexpected 'use' (T_USE)
Request URL: /isaserver/appsyncs
Stack Trace:
#0 D:\xampp\htdocs\isaserver\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 20)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 20, Array)
#2 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 20, Array)
#3 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by jmitchell38488** [comment]
Have you included the composer autoloader? Could you please copy+paste the code that you're using where you have the `T_USE` exception being thrown?

**Comment by gabrielconfused** [comment]
session_start();

```
    // To load app\Vendor\vendor\autoload.php
    require_once(APP . 'Vendor' . DS . 'vendor' . DS . 'autoload.php');

    use jmitchell38488\oauth2-fitbit\src\Provider\FitBitAuthorization;

    //require_once __DIR__ . '/vendor/autoload.php';

    $provider = new FitBitAuthorization([
        'clientId'      => '',
        'clientSecret'  => '',
        'redirectUri'   => '',
    ]);

    // 1st step: Has the user authorised yet?
    if (!isset($_SESSION['oauth2state'])) {
        $authorizationUrl = $provider->getAuthorizationUrl([
            'prompt' => FitBitAuthorization::PROMPT_CONSENT,
            'response_type' => FitBitAuthorization::RESPONSETYPE_CODE,
            'scope' => $provider->getAllScope(),
        ]);

        // Set the session state to validate in the callback
        $_SESSION['oauth2state'] = $provider->getState();

        header('Location: ' . $authorizationUrl);
        exit;

    // 2nd step: User has authorised, now lets get the refresh & access tokens
    } else if (isset($_GET['state']) && $_GET['state'] == $_SESSION['oauth2state'] && isset($_GET['code']) && !isset($_SESSION['fitbit']['oauth'])) {
        try {
            $token = base64_encode(sprintf('%s:%s', $my_client_id_from_fitbit, $my_client_secret_from_fitbit));
            $accessToken = $provider->getAccessToken('authorization_code', [
                'code'  => $_GET['code'],
                'access_token' => $_GET['code'],
                'token' => $token,
            ]);

            unset($_SESSION['oauth2state']);
            $_SESSION['fitbit']['oauth2'] = array(
                'accessToken' => $accessToken->getToken(),
                'expires' => $accessToken->getExpires(),
                'refreshToken' => $accessToken->getRefreshToken(),
            );
        } catch (Exception $ex) {
            print $ex->getMessage();
        }

    // 3rd step: Authorised, have tokens, but session needs to be refreshed
    } else if (time() > $_SESSION['fitbit']['oauth2']['expires']) {
        try {
            $token = base64_encode(sprintf('%s:%s', $my_client_id_from_fitbit, $my_client_secret_from_fitbit));
            $accessToken = $provider->getAccessToken('refresh_token', [
                'grant_type'    => FitBitAuthorization::GRANTTYPE_REFRESH,
                'access_token'  => $_SESSION['fitbit']['oauth2']['accessToken'],
                'refresh_token'  => $_SESSION['fitbit']['oauth2']['refreshToken'],
                'token'         => $token,
            ]);

            unset($_SESSION['oauth2state']);
            $_SESSION['fitbit']['oauth2'] = array(
                'accessToken' => $accessToken->getToken(),
                'expires' => $accessToken->getExpires(),
                'refreshToken' => $accessToken->getRefreshToken(),
            );
        } catch (Exception $ex) {
            print $ex->getMessage();
        }
    }
```

I used your code.
changed directories
composer autoloader???
I used composer to install this
would it matter Im just testing this locally for now?

**Comment by jmitchell38488** [comment]
Make sure that you add the 'use' statement above the autoload part. You also have an issue with the `use` statement since it's use file path rather than namespace path. Your `use` statement has to use the namespace path, since it's a language feature for namespaces.

``` php
session_start();
use Jmitchell38488\OAuth2\Client\Provider\FitBitAuthorization;
```

Changing order doesn't matter in the end as long as you correctly load the composer autoloader class.

``` php
    session_start();

    // To load app\Vendor\vendor\autoload.php
    require_once(APP . 'Vendor' . DS . 'vendor' . DS . 'autoload.php');

    use Jmitchell38488\OAuth2\Client\Provider\FitBitAuthorization;
```

**Comment by gabrielconfused** [comment]
I really appreciate the time and effort in teaching me these things
but still no dice

here is the stack trace.. 

2016-09-22 02:16:07 Error: Fatal Error (4): syntax error, unexpected 'use' (T_USE) in [D:\xampp\htdocs\isaserver\app\Controller\AppSyncsController.php, line 16]
2016-09-22 02:16:07 Error: [FatalErrorException] syntax error, unexpected 'use' (T_USE)
Request URL: /isaserver/appsyncs
Stack Trace:
#0 D:\xampp\htdocs\isaserver\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 16)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 16, Array)
#2 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 16, Array)
#3 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

is it a problem with namespaces and cakephp?

**Comment by jmitchell38488** [comment]
Here, this might make sense of it:
http://stackoverflow.com/questions/33342994/unexpected-use-t-use-when-trying-to-use-composer

Make sure that your `use` statements are at the top of the files/classes rather than in the body of the implementation.

**Comment by gabrielconfused** [comment]
Thank you so much for all of your help.
right now i am experiencing this error:
Required option not passed: "access_token"

I'm pretty sure I can figure this one out..

also side note: Peter > Chicken

**Comment by jmitchell38488** [comment]
``` php
            $token = base64_encode(sprintf('%s:%s', $my_client_id_from_fitbit, $my_client_secret_from_fitbit));
            $accessToken = $provider->getAccessToken('authorization_code', [
                'code'  => $_GET['code'],
                'access_token' => $_GET['code'],
                'token' => $token,
            ]);
```

**Comment by jmitchell38488** [comment]
Just make sure that you're storing your access token in the session so that you can retrieve it again.

**Comment by gabrielconfused** [comment]
I am using this

  $token = base64_encode(sprintf('%s:%s', $my_client_id_from_fitbit, $my_client_secret_from_fitbit));
            $accessToken = $provider->getAccessToken('authorization_code', [
                'code'  => $_GET['code'],
                'access_token' => $_GET['code'],
                'token' => $token,
            ]);

however $my_client_id_from_fitbit, $my_client_secret_from_fitbit seems to be empty

**Comment by jmitchell38488** [comment]
Yeah, you have to fill these in yourself.

**Comment by gabrielconfused** [comment]
Very Much Thankful.

now I am trying to make a request using the code you provided

$provider = new FitBit([
    'clientId'      => 'clientid',
    'clientSecret'  => 'clientsecret',
    'redirectUri'   => 'URL',
]);

```
$endpoint = $provider->getBaseApiUrl() . "user/-/profile." . FitBit::FORMAT_JSON;
```

$request = $provider->getAuthenticatedRequest(
    FitBit::METHOD_GET,
    $endpoint,
    $_SESSION['fitbit']['oauth2']['accessToken']
);

$response = $provider->getResponse($request);

I get this error:

Error: Class 'FitBit' not found 
File: D:\xampp\htdocs\isaserver\app\Controller\AppSyncsController.php  
Line: 95

errorlog

2016-09-23 01:19:06 Error: Fatal Error (1): Class 'FitBit' not found in [D:\xampp\htdocs\isaserver\app\Controller\AppSyncsController.php, line 95]
2016-09-23 01:19:06 Error: [FatalErrorException] Class 'FitBit' not found
Request URL: /isaserver/appsyncs?code=289fcdc6063f8faba66ec723621edb760f99a68e&state=nXbIAm2x6e90ysObHOpiXDkqVyh3cdSr
Stack Trace:
#0 D:\xampp\htdocs\isaserver\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Class 'FitBit' ...', 'D:\xampp\htdocs...', 95)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'FitBit' ...', 'D:\xampp\htdocs...', 95, Array)
#2 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'FitBit' ...', 'D:\xampp\htdocs...', 95, Array)
#3 D:\xampp\htdocs\isaserver\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

**Comment by gabrielconfused** [comment]
finally i got it working
however

I get this error on my server
Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'  
/league/oauth2-client/src/Grant/GrantFactory.php  
Line: 85

stack

2016-09-29 09:28:40 Error: Fatal Error (4): syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [/var/www/demo/isaserver/app/Vendor/fitbit/league/oauth2-client/src/Grant/GrantFactory.php, line 85]
2016-09-29 09:28:40 Error: [FatalErrorException] syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
Request URL: /appsyncs/fitbit
Stack Trace:
#0 /var/www/demo/isaserver/lib/Cake/Error/ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/demo/i...', 85)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/demo/i...', 85, Array)
#2 /var/www/demo/isaserver/lib/Cake/Core/App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/demo/i...', 85, Array)
#3 /var/www/demo/isaserver/lib/Cake/Core/App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}

I think the problem is that my php on the server is 5.4 any work around on this?
