### ISSUE TITLE
how to use this to write data to fitbit

### ISSUE THREAD

**Issue by gabrielconfused** [jmitchell38488/oauth2-fitbit#7]

**Comment by jmitchell38488** [comment]
Hi @gabrielconfused, you can't with this tool. This intention of this tool is to connect to and fetch from the fitbit OAUTH service.

**Comment by gabrielconfused** [comment]
thank you

**Comment by jmitchell38488** [comment]
Your mobile device will write to the fitbit services anyway. Fitbit set it up that way to force you to buy their products.

If you look through their API docs, you won't see any examples where you can post/put data:
https://dev.fitbit.com/docs/oauth2/

**Comment by gabrielconfused** [comment]
I really appreciate the effort for clarifying that
